/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 17 06:17:36 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.prog;
import edu.osu.cs362.team;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;
import org.evosuite.runtime.System;
import org.evosuite.runtime.util.SystemInUtil;


@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 

public class prog_ESTest extends prog_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 135 covered goals:
   * Goal 1. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - true
   * Goal 2. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - false
   * Goal 3. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - false
   * Goal 4. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - true
   * Goal 5. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - false
   * Goal 6. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - true
   * Goal 7. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - false
   * Goal 8. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I66 Branch 6 IFNE L53 - false
   * Goal 9. Branch edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - false in context: 
   * Goal 10. Branch edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - true in context: 
   * Goal 11. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - false in context: 
   * Goal 12. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - false in context: 
   * Goal 13. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - true in context: 
   * Goal 14. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - true in context: 
   * Goal 15. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - false in context: 
   * Goal 16. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I66 Branch 6 IFNE L53 - false in context: 
   * Goal 17. match_ups([Ledu/osu/cs362/team;I)V_org.evosuite.runtime.TooManyResourcesException_IMPLICIT
   * Goal 18. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 13
   * Goal 19. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 14
   * Goal 20. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 18
   * Goal 21. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 20
   * Goal 22. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 21
   * Goal 23. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 26
   * Goal 24. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 27
   * Goal 25. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 30
   * Goal 26. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 42
   * Goal 27. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 43
   * Goal 28. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 46
   * Goal 29. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 48
   * Goal 30. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 50
   * Goal 31. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 52
   * Goal 32. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 53
   * Goal 33. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 55
   * Goal 34. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 56
   * Goal 35. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 65
   * Goal 36. [METHOD] edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V
   * Goal 37. Weak Mutation 0: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:13 - ReplaceVariable x -> y
   * Goal 38. Weak Mutation 1: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:14 - ReplaceVariable y -> x
   * Goal 39. Weak Mutation 2: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceVariable sumX -> sumY
   * Goal 40. Weak Mutation 3: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp Negation of sumX
   * Goal 41. Weak Mutation 4: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC 1 sumX
   * Goal 42. Weak Mutation 5: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC -1 sumX
   * Goal 43. Weak Mutation 6: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceVariable sumY -> sumX
   * Goal 44. Weak Mutation 7: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp Negation of sumY
   * Goal 45. Weak Mutation 8: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC 1 sumY
   * Goal 46. Weak Mutation 9: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC -1 sumY
   * Goal 47. Weak Mutation 10: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceComparisonOperator <= -> -1
   * Goal 48. Weak Mutation 11: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceComparisonOperator <= -> <
   * Goal 49. Weak Mutation 12: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceComparisonOperator <= -> ==
   * Goal 50. Weak Mutation 13: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:20 - ReplaceVariable x -> y
   * Goal 51. Weak Mutation 14: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:21 - ReplaceVariable y -> x
   * Goal 52. Weak Mutation 15: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:26 - ReplaceVariable x -> y
   * Goal 53. Weak Mutation 16: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:27 - ReplaceVariable y -> x
   * Goal 54. Weak Mutation 27: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:42 - ReplaceComparisonOperator == -> !=
   * Goal 55. Weak Mutation 28: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant - each team played  -> 
   * Goal 56. Weak Mutation 29: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp Negation of times
   * Goal 57. Weak Mutation 30: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC 1 times
   * Goal 58. Weak Mutation 31: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC -1 times
   * Goal 59. Weak Mutation 32: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant -  rounds of games -> 
   * Goal 60. Weak Mutation 33: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceConstant - 0 -> 1
   * Goal 61. Weak Mutation 34: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable i -> times
   * Goal 62. Weak Mutation 35: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of i
   * Goal 63. Weak Mutation 36: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 i
   * Goal 64. Weak Mutation 37: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 i
   * Goal 65. Weak Mutation 38: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable times -> i
   * Goal 66. Weak Mutation 39: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of times
   * Goal 67. Weak Mutation 40: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 times
   * Goal 68. Weak Mutation 41: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 times
   * Goal 69. Weak Mutation 42: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceComparisonOperator >= -> -1
   * Goal 70. Weak Mutation 130: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable i -> times
   * Goal 71. Weak Mutation 45: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceConstant - 0 -> 1
   * Goal 72. Weak Mutation 46: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> i
   * Goal 73. Weak Mutation 47: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> times
   * Goal 74. Weak Mutation 48: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp Negation of j
   * Goal 75. Weak Mutation 49: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp IINC 1 j
   * Goal 76. Weak Mutation 50: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp IINC -1 j
   * Goal 77. Weak Mutation 51: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceComparisonOperator >= -> -1
   * Goal 78. Weak Mutation 52: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceComparisonOperator >= -> >
   * Goal 79. Weak Mutation 128: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> i
   * Goal 80. Weak Mutation 129: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> times
   * Goal 81. Weak Mutation 54: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable j -> i
   * Goal 82. Weak Mutation 55: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable j -> times
   * Goal 83. Weak Mutation 56: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp Negation of j
   * Goal 84. Weak Mutation 57: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC 1 j
   * Goal 85. Weak Mutation 58: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC -1 j
   * Goal 86. Weak Mutation 59: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> i
   * Goal 87. Weak Mutation 60: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> times
   * Goal 88. Weak Mutation 61: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> j
   * Goal 89. Weak Mutation 62: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp Negation of k
   * Goal 90. Weak Mutation 63: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC 1 k
   * Goal 91. Weak Mutation 64: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC -1 k
   * Goal 92. Weak Mutation 65: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceComparisonOperator >= -> -1
   * Goal 93. Weak Mutation 66: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceComparisonOperator >= -> >
   * Goal 94. Weak Mutation 125: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> i
   * Goal 95. Weak Mutation 126: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> times
   * Goal 96. Weak Mutation 127: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> j
   * Goal 97. Weak Mutation 68: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:52 - ReplaceConstant - 1 -> 0
   * Goal 98. Weak Mutation 69: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> i
   * Goal 99. Weak Mutation 70: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> times
   * Goal 100. Weak Mutation 71: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> j
   * Goal 101. Weak Mutation 72: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> k
   * Goal 102. Weak Mutation 73: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp Negation of num
   * Goal 103. Weak Mutation 74: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp IINC 1 num
   * Goal 104. Weak Mutation 75: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp IINC -1 num
   * Goal 105. Weak Mutation 76: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceComparisonOperator != -> -1
   * Goal 106. Weak Mutation 79: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> i
   * Goal 107. Weak Mutation 80: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> times
   * Goal 108. Weak Mutation 81: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> k
   * Goal 109. Weak Mutation 82: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> num
   * Goal 110. Weak Mutation 83: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp Negation of j
   * Goal 111. Weak Mutation 84: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp IINC 1 j
   * Goal 112. Weak Mutation 85: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp IINC -1 j
   * Goal 113. Weak Mutation 86: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceConstant - 1 -> 0
   * Goal 114. Weak Mutation 87: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> i
   * Goal 115. Weak Mutation 88: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> times
   * Goal 116. Weak Mutation 89: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> j
   * Goal 117. Weak Mutation 90: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> num
   * Goal 118. Weak Mutation 91: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - InsertUnaryOp Negation of k
   * Goal 119. Weak Mutation 92: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - InsertUnaryOp IINC 1 k
   * Goal 120. Weak Mutation 93: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - InsertUnaryOp IINC -1 k
   * Goal 121. Weak Mutation 94: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceConstant - 0 -> 1
   * Goal 122. Weak Mutation 111: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> i
   * Goal 123. Weak Mutation 112: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> times
   * Goal 124. Weak Mutation 113: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> k
   * Goal 125. Weak Mutation 114: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> num
   * Goal 126. Weak Mutation 115: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp Negation of j
   * Goal 127. Weak Mutation 116: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC 1 j
   * Goal 128. Weak Mutation 117: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC -1 j
   * Goal 129. Weak Mutation 118: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> i
   * Goal 130. Weak Mutation 119: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> times
   * Goal 131. Weak Mutation 120: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> j
   * Goal 132. Weak Mutation 121: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> num
   * Goal 133. Weak Mutation 122: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp Negation of k
   * Goal 134. Weak Mutation 123: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC 1 k
   * Goal 135. Weak Mutation 124: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC -1 k
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Random.setNextRandom(488);
      team team0 = new team();
      team[] teamArray0 = new team[9];
      teamArray0[0] = team0;
      team team1 = new team();
      teamArray0[1] = team1;
      teamArray0[2] = team0;
      teamArray0[3] = team0;
      teamArray0[4] = team0;
      teamArray0[5] = team0;
      teamArray0[6] = team0;
      teamArray0[7] = team0;
      teamArray0[8] = team0;
      // Undeclared exception!
      try { 
        prog.match_ups(teamArray0, 488);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
       //  assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  //Test case number: 1
  /*
   * 11 covered goals:
   * Goal 1. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: I8 Branch 2 IF_ICMPGE L33 - true
   * Goal 2. Branch edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: I8 Branch 2 IF_ICMPGE L33 - true in context: 
   * Goal 3. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: Line 33
   * Goal 4. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: Line 38
   * Goal 5. [METHOD] edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V
   * Goal 6. [METHODNOEX] edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V
   * Goal 7. Weak Mutation 17: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - ReplaceConstant - 0 -> 1
   * Goal 8. Weak Mutation 18: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp Negation of i
   * Goal 9. Weak Mutation 19: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp IINC 1 i
   * Goal 10. Weak Mutation 20: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp IINC -1 i
   * Goal 11. Weak Mutation 22: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - ReplaceComparisonOperator >= -> >
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      team[] teamArray0 = new team[0];
      prog.show_stats(teamArray0);
  }

  //Test case number: 2
  /*
   * 24 covered goals:
   * Goal 1. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - true
   * Goal 2. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - true in context: 
   * Goal 3. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 42
   * Goal 4. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 43
   * Goal 5. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 46
   * Goal 6. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 70
   * Goal 7. [METHOD] edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V
   * Goal 8. [METHODNOEX] edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V
   * Goal 9. Weak Mutation 27: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:42 - ReplaceComparisonOperator == -> !=
   * Goal 10. Weak Mutation 28: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant - each team played  -> 
   * Goal 11. Weak Mutation 29: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp Negation of times
   * Goal 12. Weak Mutation 30: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC 1 times
   * Goal 13. Weak Mutation 31: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC -1 times
   * Goal 14. Weak Mutation 32: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant -  rounds of games -> 
   * Goal 15. Weak Mutation 33: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 34: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable i -> times
   * Goal 17. Weak Mutation 35: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of i
   * Goal 18. Weak Mutation 36: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 i
   * Goal 19. Weak Mutation 37: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 i
   * Goal 20. Weak Mutation 38: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable times -> i
   * Goal 21. Weak Mutation 39: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of times
   * Goal 22. Weak Mutation 40: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 times
   * Goal 23. Weak Mutation 41: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 times
   * Goal 24. Weak Mutation 44: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceComparisonOperator >= -> ==
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      team[] teamArray0 = new team[0];
      prog.match_ups(teamArray0, (-1));
  }

  //Test case number: 3
  /*
   * 17 covered goals:
   * Goal 1. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - true
   * Goal 2. Branch edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - true in context: 
   * Goal 3. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 13
   * Goal 4. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 14
   * Goal 5. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 18
   * Goal 6. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 26
   * Goal 7. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 27
   * Goal 8. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 30
   * Goal 9. [METHOD] edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V
   * Goal 10. [METHODNOEX] edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V
   * Goal 11. Weak Mutation 3: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp Negation of sumX
   * Goal 12. Weak Mutation 4: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC 1 sumX
   * Goal 13. Weak Mutation 5: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC -1 sumX
   * Goal 14. Weak Mutation 7: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp Negation of sumY
   * Goal 15. Weak Mutation 8: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC 1 sumY
   * Goal 16. Weak Mutation 9: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC -1 sumY
   * Goal 17. Weak Mutation 11: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceComparisonOperator <= -> <
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Random.setNextRandom(488);
      team team0 = new team();
      prog.calc_winner(team0, team0);
  }

  //Test case number: 4
  /*
   * 7 covered goals:
   * Goal 1. show_stats([Ledu/osu/cs362/team;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: Line 33
   * Goal 3. [METHOD] edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V
   * Goal 4. Weak Mutation 17: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - ReplaceConstant - 0 -> 1
   * Goal 5. Weak Mutation 18: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp Negation of i
   * Goal 6. Weak Mutation 19: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp IINC 1 i
   * Goal 7. Weak Mutation 20: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        prog.show_stats((team[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //assertThrownBy("edu.osu.cs362.prog", e);
      }
  }

  //Test case number: 5
  /*
   * 60 covered goals:
   * Goal 1. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - false
   * Goal 2. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - false
   * Goal 3. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - false
   * Goal 4. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I66 Branch 6 IFNE L53 - false
   * Goal 5. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - false in context: 
   * Goal 6. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - false in context: 
   * Goal 7. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - false in context: 
   * Goal 8. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I66 Branch 6 IFNE L53 - false in context: 
   * Goal 9. match_ups([Ledu/osu/cs362/team;I)V_java.lang.NullPointerException_IMPLICIT
   * Goal 10. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 42
   * Goal 11. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 43
   * Goal 12. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 46
   * Goal 13. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 48
   * Goal 14. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 50
   * Goal 15. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 52
   * Goal 16. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 53
   * Goal 17. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 55
   * Goal 18. [METHOD] edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V
   * Goal 19. Weak Mutation 27: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:42 - ReplaceComparisonOperator == -> !=
   * Goal 20. Weak Mutation 28: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant - each team played  -> 
   * Goal 21. Weak Mutation 29: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp Negation of times
   * Goal 22. Weak Mutation 30: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC 1 times
   * Goal 23. Weak Mutation 31: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC -1 times
   * Goal 24. Weak Mutation 32: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant -  rounds of games -> 
   * Goal 25. Weak Mutation 33: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceConstant - 0 -> 1
   * Goal 26. Weak Mutation 34: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable i -> times
   * Goal 27. Weak Mutation 35: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of i
   * Goal 28. Weak Mutation 36: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 i
   * Goal 29. Weak Mutation 37: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 i
   * Goal 30. Weak Mutation 38: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable times -> i
   * Goal 31. Weak Mutation 39: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of times
   * Goal 32. Weak Mutation 40: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 times
   * Goal 33. Weak Mutation 41: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 times
   * Goal 34. Weak Mutation 42: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceComparisonOperator >= -> -1
   * Goal 35. Weak Mutation 45: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceConstant - 0 -> 1
   * Goal 36. Weak Mutation 47: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> times
   * Goal 37. Weak Mutation 48: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp Negation of j
   * Goal 38. Weak Mutation 49: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp IINC 1 j
   * Goal 39. Weak Mutation 50: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp IINC -1 j
   * Goal 40. Weak Mutation 51: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceComparisonOperator >= -> -1
   * Goal 41. Weak Mutation 55: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable j -> times
   * Goal 42. Weak Mutation 56: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp Negation of j
   * Goal 43. Weak Mutation 57: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC 1 j
   * Goal 44. Weak Mutation 58: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC -1 j
   * Goal 45. Weak Mutation 60: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> times
   * Goal 46. Weak Mutation 62: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp Negation of k
   * Goal 47. Weak Mutation 63: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC 1 k
   * Goal 48. Weak Mutation 64: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC -1 k
   * Goal 49. Weak Mutation 65: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceComparisonOperator >= -> -1
   * Goal 50. Weak Mutation 68: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:52 - ReplaceConstant - 1 -> 0
   * Goal 51. Weak Mutation 70: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> times
   * Goal 52. Weak Mutation 73: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp Negation of num
   * Goal 53. Weak Mutation 74: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp IINC 1 num
   * Goal 54. Weak Mutation 75: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp IINC -1 num
   * Goal 55. Weak Mutation 76: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceComparisonOperator != -> -1
   * Goal 56. Weak Mutation 80: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> times
   * Goal 57. Weak Mutation 83: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp Negation of j
   * Goal 58. Weak Mutation 84: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp IINC 1 j
   * Goal 59. Weak Mutation 85: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp IINC -1 j
   * Goal 60. Weak Mutation 86: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceConstant - 1 -> 0
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      team[] teamArray0 = new team[1];
      // Undeclared exception!
      try { 
        prog.match_ups(teamArray0, 1757);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 6
  /*
   * 40 covered goals:
   * Goal 1. edu.osu.cs362.prog.main([Ljava/lang/String;)V: I20 Branch 7 IF_ICMPGE L80 - false
   * Goal 2. Branch edu.osu.cs362.prog.main([Ljava/lang/String;)V: I20 Branch 7 IF_ICMPGE L80 - false in context: edu.osu.cs362.prog:main([Ljava/lang/String;)V
   * Goal 3. main([Ljava/lang/String;)V_org.evosuite.runtime.TooManyResourcesException_IMPLICIT
   * Goal 4. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 76
   * Goal 5. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 77
   * Goal 6. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 79
   * Goal 7. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 80
   * Goal 8. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 81
   * Goal 9. [METHOD] edu.osu.cs362.prog.main([Ljava/lang/String;)V
   * Goal 10. Weak Mutation 131: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 0
   * Goal 11. Weak Mutation 132: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 1
   * Goal 12. Weak Mutation 133: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> -1
   * Goal 13. Weak Mutation 134: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 3
   * Goal 14. Weak Mutation 135: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 5
   * Goal 15. Weak Mutation 136: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 0
   * Goal 16. Weak Mutation 137: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 1
   * Goal 17. Weak Mutation 138: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> -1
   * Goal 18. Weak Mutation 139: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 2
   * Goal 19. Weak Mutation 140: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 4
   * Goal 20. Weak Mutation 141: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - ReplaceVariable num_teams -> num_rounds
   * Goal 21. Weak Mutation 142: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - InsertUnaryOp Negation of num_teams
   * Goal 22. Weak Mutation 143: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 num_teams
   * Goal 23. Weak Mutation 144: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 num_teams
   * Goal 24. Weak Mutation 145: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceConstant - 0 -> 1
   * Goal 25. Weak Mutation 146: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable i -> num_rounds
   * Goal 26. Weak Mutation 147: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable i -> num_teams
   * Goal 27. Weak Mutation 148: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp Negation of i
   * Goal 28. Weak Mutation 149: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC 1 i
   * Goal 29. Weak Mutation 150: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC -1 i
   * Goal 30. Weak Mutation 151: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable num_teams -> i
   * Goal 31. Weak Mutation 152: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable num_teams -> num_rounds
   * Goal 32. Weak Mutation 153: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp Negation of num_teams
   * Goal 33. Weak Mutation 154: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC 1 num_teams
   * Goal 34. Weak Mutation 155: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC -1 num_teams
   * Goal 35. Weak Mutation 156: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceComparisonOperator >= -> -1
   * Goal 36. Weak Mutation 159: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - ReplaceVariable i -> num_rounds
   * Goal 37. Weak Mutation 160: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - ReplaceVariable i -> num_teams
   * Goal 38. Weak Mutation 161: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - InsertUnaryOp Negation of i
   * Goal 39. Weak Mutation 162: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - InsertUnaryOp IINC 1 i
   * Goal 40. Weak Mutation 163: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        prog.main((String[]) null);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         //assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  //Test case number: 7
  /*
   * 3 covered goals:
   * Goal 1. calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 13
   * Goal 3. [METHOD] edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        prog.calc_winner((team) null, (team) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 8
  /*
   * 221 covered goals:
   * Goal 1. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - true
   * Goal 2. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - false
   * Goal 3. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: I8 Branch 2 IF_ICMPGE L33 - true
   * Goal 4. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: I8 Branch 2 IF_ICMPGE L33 - false
   * Goal 5. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - true
   * Goal 6. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - false
   * Goal 7. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - true
   * Goal 8. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - false
   * Goal 9. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - true
   * Goal 10. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - false
   * Goal 11. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I66 Branch 6 IFNE L53 - false
   * Goal 12. edu.osu.cs362.prog.main([Ljava/lang/String;)V: I20 Branch 7 IF_ICMPGE L80 - true
   * Goal 13. edu.osu.cs362.prog.main([Ljava/lang/String;)V: I20 Branch 7 IF_ICMPGE L80 - false
   * Goal 14. Branch edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - false in context: 
   * Goal 15. Branch edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: I14 Branch 1 IF_ICMPLE L18 - true in context: 
   * Goal 16. Branch edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: I8 Branch 2 IF_ICMPGE L33 - false in context: 
   * Goal 17. Branch edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: I8 Branch 2 IF_ICMPGE L33 - true in context: 
   * Goal 18. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - true in context: 
   * Goal 19. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I38 Branch 3 IF_ICMPGE L46 - false in context: 
   * Goal 20. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - false in context: 
   * Goal 21. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I47 Branch 4 IF_ICMPGE L48 - true in context: 
   * Goal 22. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - true in context: 
   * Goal 23. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I56 Branch 5 IF_ICMPGE L50 - false in context: 
   * Goal 24. Branch edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: I66 Branch 6 IFNE L53 - false in context: 
   * Goal 25. Branch edu.osu.cs362.prog.main([Ljava/lang/String;)V: I20 Branch 7 IF_ICMPGE L80 - false in context: edu.osu.cs362.prog:main([Ljava/lang/String;)V
   * Goal 26. Branch edu.osu.cs362.prog.main([Ljava/lang/String;)V: I20 Branch 7 IF_ICMPGE L80 - true in context: edu.osu.cs362.prog:main([Ljava/lang/String;)V
   * Goal 27. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 13
   * Goal 28. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 14
   * Goal 29. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 18
   * Goal 30. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 20
   * Goal 31. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 21
   * Goal 32. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 26
   * Goal 33. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 27
   * Goal 34. edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V: Line 30
   * Goal 35. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 76
   * Goal 36. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 77
   * Goal 37. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 79
   * Goal 38. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 80
   * Goal 39. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 81
   * Goal 40. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 84
   * Goal 41. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 85
   * Goal 42. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 86
   * Goal 43. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 87
   * Goal 44. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 89
   * Goal 45. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 90
   * Goal 46. edu.osu.cs362.prog.main([Ljava/lang/String;)V: Line 91
   * Goal 47. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 42
   * Goal 48. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 43
   * Goal 49. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 46
   * Goal 50. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 48
   * Goal 51. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 50
   * Goal 52. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 52
   * Goal 53. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 53
   * Goal 54. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 55
   * Goal 55. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 56
   * Goal 56. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 65
   * Goal 57. edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V: Line 70
   * Goal 58. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: Line 33
   * Goal 59. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: Line 35
   * Goal 60. edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V: Line 38
   * Goal 61. [METHOD] edu.osu.cs362.prog.main([Ljava/lang/String;)V
   * Goal 62. [METHODNOEX] edu.osu.cs362.prog.main([Ljava/lang/String;)V
   * Goal 63. Weak Mutation 0: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:13 - ReplaceVariable x -> y
   * Goal 64. Weak Mutation 1: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:14 - ReplaceVariable y -> x
   * Goal 65. Weak Mutation 2: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceVariable sumX -> sumY
   * Goal 66. Weak Mutation 3: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp Negation of sumX
   * Goal 67. Weak Mutation 4: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC 1 sumX
   * Goal 68. Weak Mutation 5: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC -1 sumX
   * Goal 69. Weak Mutation 6: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceVariable sumY -> sumX
   * Goal 70. Weak Mutation 7: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp Negation of sumY
   * Goal 71. Weak Mutation 8: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC 1 sumY
   * Goal 72. Weak Mutation 9: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - InsertUnaryOp IINC -1 sumY
   * Goal 73. Weak Mutation 10: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceComparisonOperator <= -> -1
   * Goal 74. Weak Mutation 11: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:18 - ReplaceComparisonOperator <= -> <
   * Goal 75. Weak Mutation 13: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:20 - ReplaceVariable x -> y
   * Goal 76. Weak Mutation 14: edu.osu.cs362.prog.calc_winner(Ledu/osu/cs362/team;Ledu/osu/cs362/team;)V:21 - ReplaceVariable y -> x
   * Goal 77. Weak Mutation 17: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - ReplaceConstant - 0 -> 1
   * Goal 78. Weak Mutation 18: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp Negation of i
   * Goal 79. Weak Mutation 19: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp IINC 1 i
   * Goal 80. Weak Mutation 20: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - InsertUnaryOp IINC -1 i
   * Goal 81. Weak Mutation 21: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - ReplaceComparisonOperator >= -> -1
   * Goal 82. Weak Mutation 22: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:33 - ReplaceComparisonOperator >= -> >
   * Goal 83. Weak Mutation 24: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:35 - InsertUnaryOp Negation of i
   * Goal 84. Weak Mutation 25: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:35 - InsertUnaryOp IINC 1 i
   * Goal 85. Weak Mutation 26: edu.osu.cs362.prog.show_stats([Ledu/osu/cs362/team;)V:35 - InsertUnaryOp IINC -1 i
   * Goal 86. Weak Mutation 27: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:42 - ReplaceComparisonOperator == -> !=
   * Goal 87. Weak Mutation 28: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant - each team played  -> 
   * Goal 88. Weak Mutation 29: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp Negation of times
   * Goal 89. Weak Mutation 30: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC 1 times
   * Goal 90. Weak Mutation 31: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - InsertUnaryOp IINC -1 times
   * Goal 91. Weak Mutation 32: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:43 - ReplaceConstant -  rounds of games -> 
   * Goal 92. Weak Mutation 33: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceConstant - 0 -> 1
   * Goal 93. Weak Mutation 34: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable i -> times
   * Goal 94. Weak Mutation 35: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of i
   * Goal 95. Weak Mutation 36: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 i
   * Goal 96. Weak Mutation 37: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 i
   * Goal 97. Weak Mutation 38: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable times -> i
   * Goal 98. Weak Mutation 39: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp Negation of times
   * Goal 99. Weak Mutation 40: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC 1 times
   * Goal 100. Weak Mutation 41: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - InsertUnaryOp IINC -1 times
   * Goal 101. Weak Mutation 42: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceComparisonOperator >= -> -1
   * Goal 102. Weak Mutation 43: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceComparisonOperator >= -> >
   * Goal 103. Weak Mutation 130: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:46 - ReplaceVariable i -> times
   * Goal 104. Weak Mutation 45: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceConstant - 0 -> 1
   * Goal 105. Weak Mutation 46: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> i
   * Goal 106. Weak Mutation 47: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> times
   * Goal 107. Weak Mutation 48: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp Negation of j
   * Goal 108. Weak Mutation 49: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp IINC 1 j
   * Goal 109. Weak Mutation 50: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - InsertUnaryOp IINC -1 j
   * Goal 110. Weak Mutation 51: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceComparisonOperator >= -> -1
   * Goal 111. Weak Mutation 52: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceComparisonOperator >= -> >
   * Goal 112. Weak Mutation 128: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> i
   * Goal 113. Weak Mutation 129: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:48 - ReplaceVariable j -> times
   * Goal 114. Weak Mutation 54: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable j -> i
   * Goal 115. Weak Mutation 55: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable j -> times
   * Goal 116. Weak Mutation 56: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp Negation of j
   * Goal 117. Weak Mutation 57: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC 1 j
   * Goal 118. Weak Mutation 58: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC -1 j
   * Goal 119. Weak Mutation 59: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> i
   * Goal 120. Weak Mutation 60: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> times
   * Goal 121. Weak Mutation 61: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> j
   * Goal 122. Weak Mutation 62: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp Negation of k
   * Goal 123. Weak Mutation 63: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC 1 k
   * Goal 124. Weak Mutation 64: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - InsertUnaryOp IINC -1 k
   * Goal 125. Weak Mutation 65: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceComparisonOperator >= -> -1
   * Goal 126. Weak Mutation 66: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceComparisonOperator >= -> >
   * Goal 127. Weak Mutation 125: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> i
   * Goal 128. Weak Mutation 126: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> times
   * Goal 129. Weak Mutation 127: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:50 - ReplaceVariable k -> j
   * Goal 130. Weak Mutation 68: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:52 - ReplaceConstant - 1 -> 0
   * Goal 131. Weak Mutation 69: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> i
   * Goal 132. Weak Mutation 70: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> times
   * Goal 133. Weak Mutation 71: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> j
   * Goal 134. Weak Mutation 72: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceVariable num -> k
   * Goal 135. Weak Mutation 73: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp Negation of num
   * Goal 136. Weak Mutation 74: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp IINC 1 num
   * Goal 137. Weak Mutation 75: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - InsertUnaryOp IINC -1 num
   * Goal 138. Weak Mutation 76: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:53 - ReplaceComparisonOperator != -> -1
   * Goal 139. Weak Mutation 79: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> i
   * Goal 140. Weak Mutation 80: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> times
   * Goal 141. Weak Mutation 81: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> k
   * Goal 142. Weak Mutation 82: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceVariable j -> num
   * Goal 143. Weak Mutation 83: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp Negation of j
   * Goal 144. Weak Mutation 84: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp IINC 1 j
   * Goal 145. Weak Mutation 85: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - InsertUnaryOp IINC -1 j
   * Goal 146. Weak Mutation 86: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:55 - ReplaceConstant - 1 -> 0
   * Goal 147. Weak Mutation 87: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> i
   * Goal 148. Weak Mutation 88: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> times
   * Goal 149. Weak Mutation 89: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> j
   * Goal 150. Weak Mutation 90: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceVariable k -> num
   * Goal 151. Weak Mutation 91: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - InsertUnaryOp Negation of k
   * Goal 152. Weak Mutation 92: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - InsertUnaryOp IINC 1 k
   * Goal 153. Weak Mutation 93: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - InsertUnaryOp IINC -1 k
   * Goal 154. Weak Mutation 94: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:56 - ReplaceConstant - 0 -> 1
   * Goal 155. Weak Mutation 111: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> i
   * Goal 156. Weak Mutation 112: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> times
   * Goal 157. Weak Mutation 113: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> k
   * Goal 158. Weak Mutation 114: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable j -> num
   * Goal 159. Weak Mutation 115: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp Negation of j
   * Goal 160. Weak Mutation 116: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC 1 j
   * Goal 161. Weak Mutation 117: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC -1 j
   * Goal 162. Weak Mutation 118: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> i
   * Goal 163. Weak Mutation 119: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> times
   * Goal 164. Weak Mutation 120: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> j
   * Goal 165. Weak Mutation 121: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - ReplaceVariable k -> num
   * Goal 166. Weak Mutation 122: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp Negation of k
   * Goal 167. Weak Mutation 123: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC 1 k
   * Goal 168. Weak Mutation 124: edu.osu.cs362.prog.match_ups([Ledu/osu/cs362/team;I)V:65 - InsertUnaryOp IINC -1 k
   * Goal 169. Weak Mutation 131: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 0
   * Goal 170. Weak Mutation 132: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 1
   * Goal 171. Weak Mutation 133: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> -1
   * Goal 172. Weak Mutation 134: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 3
   * Goal 173. Weak Mutation 135: edu.osu.cs362.prog.main([Ljava/lang/String;)V:76 - ReplaceConstant - 4 -> 5
   * Goal 174. Weak Mutation 136: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 0
   * Goal 175. Weak Mutation 137: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 1
   * Goal 176. Weak Mutation 138: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> -1
   * Goal 177. Weak Mutation 139: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 2
   * Goal 178. Weak Mutation 140: edu.osu.cs362.prog.main([Ljava/lang/String;)V:77 - ReplaceConstant - 3 -> 4
   * Goal 179. Weak Mutation 141: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - ReplaceVariable num_teams -> num_rounds
   * Goal 180. Weak Mutation 142: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - InsertUnaryOp Negation of num_teams
   * Goal 181. Weak Mutation 143: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - InsertUnaryOp IINC 1 num_teams
   * Goal 182. Weak Mutation 144: edu.osu.cs362.prog.main([Ljava/lang/String;)V:79 - InsertUnaryOp IINC -1 num_teams
   * Goal 183. Weak Mutation 145: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceConstant - 0 -> 1
   * Goal 184. Weak Mutation 146: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable i -> num_rounds
   * Goal 185. Weak Mutation 147: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable i -> num_teams
   * Goal 186. Weak Mutation 148: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp Negation of i
   * Goal 187. Weak Mutation 149: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC 1 i
   * Goal 188. Weak Mutation 150: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC -1 i
   * Goal 189. Weak Mutation 151: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable num_teams -> i
   * Goal 190. Weak Mutation 152: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable num_teams -> num_rounds
   * Goal 191. Weak Mutation 153: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp Negation of num_teams
   * Goal 192. Weak Mutation 154: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC 1 num_teams
   * Goal 193. Weak Mutation 155: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - InsertUnaryOp IINC -1 num_teams
   * Goal 194. Weak Mutation 156: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceComparisonOperator >= -> -1
   * Goal 195. Weak Mutation 157: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceComparisonOperator >= -> >
   * Goal 196. Weak Mutation 164: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable i -> num_rounds
   * Goal 197. Weak Mutation 165: edu.osu.cs362.prog.main([Ljava/lang/String;)V:80 - ReplaceVariable i -> num_teams
   * Goal 198. Weak Mutation 159: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - ReplaceVariable i -> num_rounds
   * Goal 199. Weak Mutation 160: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - ReplaceVariable i -> num_teams
   * Goal 200. Weak Mutation 161: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - InsertUnaryOp Negation of i
   * Goal 201. Weak Mutation 162: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - InsertUnaryOp IINC 1 i
   * Goal 202. Weak Mutation 163: edu.osu.cs362.prog.main([Ljava/lang/String;)V:81 - InsertUnaryOp IINC -1 i
   * Goal 203. Weak Mutation 166: edu.osu.cs362.prog.main([Ljava/lang/String;)V:84 - ReplaceConstant - 0 -> 1
   * Goal 204. Weak Mutation 167: edu.osu.cs362.prog.main([Ljava/lang/String;)V:84 - ReplaceConstant - sharks -> 
   * Goal 205. Weak Mutation 168: edu.osu.cs362.prog.main([Ljava/lang/String;)V:85 - ReplaceConstant - 1 -> 0
   * Goal 206. Weak Mutation 169: edu.osu.cs362.prog.main([Ljava/lang/String;)V:85 - ReplaceConstant - gators -> 
   * Goal 207. Weak Mutation 170: edu.osu.cs362.prog.main([Ljava/lang/String;)V:86 - ReplaceConstant - 2 -> 0
   * Goal 208. Weak Mutation 171: edu.osu.cs362.prog.main([Ljava/lang/String;)V:86 - ReplaceConstant - 2 -> 1
   * Goal 209. Weak Mutation 172: edu.osu.cs362.prog.main([Ljava/lang/String;)V:86 - ReplaceConstant - 2 -> -1
   * Goal 210. Weak Mutation 173: edu.osu.cs362.prog.main([Ljava/lang/String;)V:86 - ReplaceConstant - 2 -> 3
   * Goal 211. Weak Mutation 174: edu.osu.cs362.prog.main([Ljava/lang/String;)V:86 - ReplaceConstant - knights -> 
   * Goal 212. Weak Mutation 175: edu.osu.cs362.prog.main([Ljava/lang/String;)V:87 - ReplaceConstant - 3 -> 0
   * Goal 213. Weak Mutation 176: edu.osu.cs362.prog.main([Ljava/lang/String;)V:87 - ReplaceConstant - 3 -> 1
   * Goal 214. Weak Mutation 177: edu.osu.cs362.prog.main([Ljava/lang/String;)V:87 - ReplaceConstant - 3 -> -1
   * Goal 215. Weak Mutation 178: edu.osu.cs362.prog.main([Ljava/lang/String;)V:87 - ReplaceConstant - 3 -> 2
   * Goal 216. Weak Mutation 179: edu.osu.cs362.prog.main([Ljava/lang/String;)V:87 - ReplaceConstant - 3 -> 4
   * Goal 217. Weak Mutation 180: edu.osu.cs362.prog.main([Ljava/lang/String;)V:87 - ReplaceConstant - divers -> 
   * Goal 218. Weak Mutation 181: edu.osu.cs362.prog.main([Ljava/lang/String;)V:89 - ReplaceVariable num_rounds -> num_teams
   * Goal 219. Weak Mutation 182: edu.osu.cs362.prog.main([Ljava/lang/String;)V:89 - InsertUnaryOp Negation of num_rounds
   * Goal 220. Weak Mutation 183: edu.osu.cs362.prog.main([Ljava/lang/String;)V:89 - InsertUnaryOp IINC 1 num_rounds
   * Goal 221. Weak Mutation 184: edu.osu.cs362.prog.main([Ljava/lang/String;)V:89 - InsertUnaryOp IINC -1 num_rounds
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Random.setNextRandom(488);
      String[] stringArray0 = new String[5];
      prog.main(stringArray0);
  }

  //Test case number: 9
  /*
   * 4 covered goals:
   * Goal 1. edu.osu.cs362.prog.<init>()V: root-Branch
   * Goal 2. Branch edu.osu.cs362.prog.<init>()V: root-Branch in context: edu.osu.cs362.prog:<init>()V
   * Goal 3. [METHOD] edu.osu.cs362.prog.<init>()V
   * Goal 4. [METHODNOEX] edu.osu.cs362.prog.<init>()V
   */

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      prog<Integer> prog0 = new prog<Integer>();
  }
}
